### ISSUE TITLE
Sparse Matrix support

### ISSUE THREAD

**Issue by davemcg** [willtownes/glmpca#11]
Are there any plans for `glmpca` to support sparse matrices? 

Thanks,
David

**Comment by willtownes** [comment]
Thanks for asking! Yes, we plan to implement this. It will require a modification to the optimization algorithm though since even if we accept a sparse data matrix, the current algorithm instantiates several dense matrices of the same size as the dense version of the data matrix within each iteration (for details, see https://arxiv.org/abs/1907.02647 ). We do have some ideas of how to do it, it's just a matter of finding time to implement and test. 

In the meantime, you can always reduce the size of the sparse matrix by using [deviance for feature selection](https://github.com/willtownes/scrna2019/blob/master/util/functions_genefilter.R#L6) (we will be releasing this as part of a bioconductor package soon for more convenience). If you have say 100,000 cells and you can subset down to say 2,000 highly informative genes by deviance, this might be enough to make the dense version of the data matrix still fit in memory.

**Comment by davemcg** [comment]
Thanks Will,

I actually was going to follow up with a Q on how to calc the deviance! I've been using Seurat's HVG test and was curious how the deviance calc would change the feature selection.

**Comment by davemcg** [comment]
Darn, I tried running `filterDev` as:
`deviance <- filterDev(sce, nkeep = 2000, dev = 'binomial', ret = 'ranks')`  with a 14,500 x 450,000 `sce` and I got the dreaded `cholmod` error.

**Comment by willtownes** [comment]
hmm, let me see if I can reproduce that error. What is the fraction of zeros in your data? Something like `1-mean(counts(sce)>0)` ?

**Comment by willtownes** [comment]
also, what happens if you set dev="poisson" ?

**Comment by davemcg** [comment]
Thanks.

I'm running `compute_gene_info(counts(sce),gmeta=rowData(sce),mod='binomial')` right now and seeing if that completes. It's currently using 100GB of RAM.

I'll get you the info (and the sce object) when that finishes/fails.

**Comment by willtownes** [comment]
Regarding computation of the deviance, a cleaned-up implementation is now available via the [scry bioconductor package](https://bioconductor.org/packages/release/bioc/html/scry.html) and in the [development version](https://github.com/kstreet13/scry) we are working to make it operate on sparse matrices and disk-based delayedArray objects.

Regarding GLM-PCA support for sparse matrices, I am currently testing a new stochastic gradient method which will allow optimization while using only minibatches of cells at each iteration. This will avoid instantiating any large dense objects in memory. I will post another notice here when it's released.

**Comment by willtownes** [comment]
glmpca now supports large sparse matrices with memoized and stochastic gradient optimizers. It's installable from github (version 0.2.0)
