### ISSUE TITLE
Variance explained

### ISSUE THREAD

**Issue by frederikziebell** [willtownes/glmpca#14]
Is it possible, as in traditional PCA, to calculate the fraction of variance explained by each of the principal components?

**Comment by willtownes** [comment]
Hi thanks for your question. It's not possible to directly compute variance explained for GLM-PCA due to the nonlinear link function. However, there are two possible alternatives.

1. You can look at the L2 norm of each column of the factors to make elbow plots and/or to rank the factors in order of importance. The loadings matrix is orthonormal just like PCA. We always return the factors in decreasing L2 norm by default. I believe in standard PCA there is a 1-1 mapping between L2 norm of the PCs and variance explained but I can't remember the exact formula.
2. You could try something like "deviance explained" as described in a recent preprint by Germain et al https://www.biorxiv.org/content/10.1101/2020.02.02.930578v1.abstract . I believe they used a function from edgeR to compute this. It might require re-fitting the model with various choices of L, I'm not sure.

**Comment by willtownes** [comment]
The new [Seurat wrapper for GLM-PCA](https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/glmpca.html) (see also the [source code](https://github.com/satijalab/seurat-wrappers/blob/master/R/glmpca.R#L58)) stores the L2 norm of each column of the factors by default. The L2 norm can also be computed by 
```
sqrt(colSums(fit$factors^2))
```
where fit is the object returned by calling `glmpca`
